apiVersion: apps/v1
kind: Deployment
metadata:
  name: transform-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transform
  template:
    metadata:
      labels:
        app: transform
    spec:
      containers:
      - name: transform
        image: my-username/transform:latest
        env:
        - name: INPUT_QUEUE
          value: split_csv_queue
        - name: OUTPUT_QUEUE
          value: transform_queue
        - name: GRAFTERIZER_EXECUTABLE_PATH
          value: "/path/to/grafterizer/executable"
