apiVersion: apps/v1
kind: Deployment
metadata:
  name: unzip-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unzip
  template:
    metadata:
      labels:
        app: unzip
    spec:
      containers:
      - name: unzip
        image: my-username/unzip:latest
        env:
        - name: OUTPUT_QUEUE
          value: unzip_tsv_queue
